[project]
id = ""

[functions.send-notification]
verify_jwt = true

[functions.facebook-oauth-callback]
verify_jwt = true

[functions.instagram-oauth-callback]
verify_jwt = true

[functions.publish-to-facebook]
verify_jwt = true
