import React, { useState, useEffect } from 'react';
import { X, Mail, Search, Send, Download, AlertTriangle, Check } from 'lucide-react';
import { supabase } from '../utils/supabase';
import { Member } from '../types/member';
import { Avatar } from './ui/Avatar';
import { MemberSelect } from './ui/MemberSelect';

interface ShareRaceResultsModalProps {
  isOpen: boolean;
  onClose: () => void;
  eventData: {
    title: string;
    date: string;
    venue: string;
    raceClass: string;
    raceFormat: string;
    clubId?: string;
  };
  raceReport: string;
  resultsImage?: string;
  darkMode: boolean;
}

export const ShareRaceResultsModal: React.FC<ShareRaceResultsModalProps> = ({
  isOpen,
  onClose,
  eventData,
  raceReport,
  resultsImage,
  darkMode
}) => {
  const [recipientType, setRecipientType] = useState<'all' | 'selected' | 'individual'>('all');
  const [members, setMembers] = useState<Member[]>([]);
  const [selectedMembers, setSelectedMembers] = useState<string[]>([]);
  const [individualRecipient, setIndividualRecipient] = useState<string>('');
  const [searchTerm, setSearchTerm] = useState('');
  const [subject, setSubject] = useState(`Race Results: ${eventData.title}`);
  const [includeAttachment, setIncludeAttachment] = useState(true);
  const [loading, setLoading] = useState(true);
  const [sending, setSending] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);

  useEffect(() => {
    if (isOpen && eventData.clubId) {
      fetchMembers();
    }
  }, [isOpen, eventData.clubId]);

  const fetchMembers = async () => {
    try {
      setLoading(true);

      const { data, error } = await supabase
        .from('members')
        .select('id, first_name, last_name, email, avatar_url')
        .eq('club_id', eventData.clubId)
        .order('first_name', { ascending: true });

      if (error) throw error;

      // Filter out members without email addresses
      const membersWithEmail = (data || []).filter(member => member.email);
      setMembers(membersWithEmail);
    } catch (err) {
      console.error('Error fetching members:', err);
      setError('Failed to load members');
    } finally {
      setLoading(false);
    }
  };

  const handleShareResults = async () => {
    try {
      setSending(true);
      setError(null);

      // Determine recipients based on selection
      let recipients: string[] = [];

      if (recipientType === 'all') {
        recipients = members.map(member => member.id);
      } else if (recipientType === 'selected') {
        recipients = selectedMembers;
      } else if (recipientType === 'individual') {
        recipients = [individualRecipient];
      }

      if (recipients.length === 0) {
        setError('Please select at least one recipient');
        setSending(false);
        return;
      }

      // Get member details for recipients
      const recipientMembers = members.filter(m => recipients.includes(m.id));

      // Prepare email body with race report
      const emailBody = `
<div style="margin-bottom: 24px;">
<h2 style="color: #1f2937; margin-bottom: 16px;">${eventData.title}</h2>
<p style="color: #6b7280; margin-bottom: 8px;">${eventData.date} | ${eventData.venue}</p>
<p style="color: #6b7280; margin-bottom: 24px;">${eventData.raceClass} ${eventData.raceFormat}</p>
</div>

<div style="white-space: pre-wrap; line-height: 1.7; color: #374151; margin-bottom: 24px;">
${raceReport}
</div>

${includeAttachment && resultsImage ? `
<div style="margin-top: 24px; margin-bottom: 24px;">
<img src="${resultsImage}" alt="Race Results" style="max-width: 100%; height: auto; border-radius: 8px; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);" />
</div>
` : ''}

<hr style="border: none; border-top: 1px solid #e5e7eb; margin: 24px 0;" />

<p style="color: #9ca3af; font-size: 14px; margin-bottom: 0;">
Results generated by Alfie PRO - RC Yacht Management Software
</p>
      `.trim();

      // Format recipients for the edge function
      const formattedRecipients = recipientMembers.map(member => ({
        user_id: member.id,
        email: member.email,
        name: `${member.first_name} ${member.last_name}`,
        first_name: member.first_name,
        last_name: member.last_name
      }));

      // Call edge function to send emails
      const { error: sendError } = await supabase.functions.invoke('send-notification', {
        body: {
          type: 'race_results',
          club_id: eventData.clubId,
          recipients: formattedRecipients,
          subject: subject,
          body: emailBody,
          send_email: true,
          club_name: eventData.title,
          link_url: `/results`
        }
      });

      if (sendError) throw sendError;

      setSuccess(`Results shared with ${recipients.length} member${recipients.length !== 1 ? 's' : ''}`);

      // Reset form after successful send
      setTimeout(() => {
        setSuccess(null);
        onClose();
      }, 2000);
    } catch (err) {
      console.error('Error sharing results:', err);
      setError(err instanceof Error ? err.message : 'Failed to share results');
    } finally {
      setSending(false);
    }
  };

  const toggleMemberSelection = (memberId: string) => {
    if (selectedMembers.includes(memberId)) {
      setSelectedMembers(selectedMembers.filter(id => id !== memberId));
    } else {
      setSelectedMembers([...selectedMembers, memberId]);
    }
  };

  // Filter members based on search term
  const filteredMembers = members.filter(member => {
    const fullName = `${member.first_name} ${member.last_name}`.toLowerCase();
    return fullName.includes(searchTerm.toLowerCase()) ||
           (member.email && member.email.toLowerCase().includes(searchTerm.toLowerCase()));
  });

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="w-full max-w-3xl bg-gradient-to-br from-slate-900 to-slate-800 rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh] border border-slate-700/50">
        <div className="flex items-center justify-between px-8 py-6 bg-gradient-to-r from-slate-800/80 to-slate-700/80 border-b border-slate-600/50">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-blue-500/10 border border-blue-500/20">
              <Mail className="text-blue-400" size={24} />
            </div>
            <h2 className="text-2xl font-bold text-white">Email Race Results</h2>
          </div>
          <button
            onClick={onClose}
            className="rounded-lg p-2 text-slate-400 hover:text-white hover:bg-slate-700/50 transition-all"
          >
            <X size={22} />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto p-6">
          {error && (
            <div className="mb-6 p-4 rounded-lg bg-red-900/20 border border-red-900/30">
              <div className="flex">
                <div className="flex-shrink-0">
                  <AlertTriangle className="h-5 w-5 text-red-400" aria-hidden="true" />
                </div>
                <div className="ml-3">
                  <p className="text-sm text-red-300">{error}</p>
                </div>
              </div>
            </div>
          )}

          {success && (
            <div className="mb-6 p-4 rounded-lg bg-green-900/20 border border-green-900/30">
              <div className="flex">
                <div className="flex-shrink-0">
                  <Check className="h-5 w-5 text-green-400" aria-hidden="true" />
                </div>
                <div className="ml-3">
                  <p className="text-sm text-green-300">{success}</p>
                </div>
              </div>
            </div>
          )}

          <div className="space-y-6">
            <div className="p-5 rounded-xl bg-gradient-to-br from-slate-800/60 to-slate-700/40 border border-slate-600/50">
              <h4 className="text-sm font-semibold text-slate-300 mb-3">Race Details</h4>
              <p className="text-white font-semibold text-lg">{eventData.title}</p>
              <p className="text-slate-300 mt-1">{eventData.date}</p>
              <p className="text-slate-300">{eventData.venue}</p>
              <p className="text-slate-400 text-sm mt-2">{eventData.raceClass} {eventData.raceFormat}</p>
            </div>

            <div>
              <label className="block text-sm font-medium text-slate-300 mb-2">
                Recipients
              </label>
              <div className="space-y-3">
                <div className="flex items-center gap-3">
                  <input
                    type="radio"
                    id="all-members"
                    checked={recipientType === 'all'}
                    onChange={() => setRecipientType('all')}
                    className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-slate-600 rounded"
                  />
                  <label htmlFor="all-members" className="text-slate-300">
                    All Club Members ({members.length})
                  </label>
                </div>

                <div className="flex items-center gap-3">
                  <input
                    type="radio"
                    id="selected-members"
                    checked={recipientType === 'selected'}
                    onChange={() => setRecipientType('selected')}
                    className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-slate-600 rounded"
                  />
                  <label htmlFor="selected-members" className="text-slate-300">
                    Selected Members ({selectedMembers.length})
                  </label>
                </div>

                <div className="flex items-center gap-3">
                  <input
                    type="radio"
                    id="individual-member"
                    checked={recipientType === 'individual'}
                    onChange={() => setRecipientType('individual')}
                    className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-slate-600 rounded"
                  />
                  <label htmlFor="individual-member" className="text-slate-300">
                    Individual Member
                  </label>
                </div>

                {recipientType === 'individual' && (
                  <div className="ml-7">
                    <MemberSelect
                      members={members}
                      value={individualRecipient}
                      onChange={setIndividualRecipient}
                      placeholder="Select a member"
                      allowEmpty={false}
                    />
                  </div>
                )}

                {recipientType === 'selected' && (
                  <div className="ml-7 mt-2">
                    <div className="mb-2">
                      <div className="relative">
                        <Search
                          size={18}
                          className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"
                        />
                        <input
                          type="text"
                          placeholder="Search members..."
                          value={searchTerm}
                          onChange={(e) => setSearchTerm(e.target.value)}
                          className="w-full pl-10 pr-4 py-2 bg-slate-700 text-slate-200 placeholder-slate-400 rounded-lg"
                        />
                      </div>
                    </div>

                    <div className="max-h-60 overflow-y-auto border border-slate-600 rounded-lg">
                      {loading ? (
                        <div className="text-center py-4">
                          <div className="animate-spin rounded-full h-6 w-6 border-b-2 border-blue-500 mx-auto"></div>
                        </div>
                      ) : filteredMembers.length === 0 ? (
                        <div className="text-center py-4 text-slate-400">
                          No members found
                        </div>
                      ) : (
                        <div className="divide-y divide-slate-700/50">
                          {filteredMembers.map(member => (
                            <div
                              key={member.id}
                              className="flex items-center justify-between p-4 hover:bg-slate-700/30 transition-colors cursor-pointer"
                              onClick={() => toggleMemberSelection(member.id)}
                            >
                              <div className="flex items-center gap-3 flex-1 min-w-0">
                                <Avatar
                                  firstName={member.first_name}
                                  lastName={member.last_name}
                                  imageUrl={member.avatar_url}
                                  size="md"
                                />
                                <div className="flex-1 min-w-0">
                                  <div className="font-semibold text-white truncate">
                                    {member.first_name} {member.last_name}
                                  </div>
                                  {member.email && (
                                    <div className="text-sm text-slate-400 truncate">
                                      {member.email}
                                    </div>
                                  )}
                                </div>
                              </div>
                              <div className="flex-shrink-0">
                                <input
                                  type="checkbox"
                                  checked={selectedMembers.includes(member.id)}
                                  onChange={(e) => {
                                    e.stopPropagation();
                                    toggleMemberSelection(member.id);
                                  }}
                                  className="h-5 w-5 rounded border-slate-600 text-blue-600 focus:ring-blue-500 cursor-pointer"
                                />
                              </div>
                            </div>
                          ))}
                        </div>
                      )}
                    </div>

                    {selectedMembers.length > 0 && (
                      <div className="mt-2 text-sm text-slate-400">
                        {selectedMembers.length} member{selectedMembers.length !== 1 ? 's' : ''} selected
                      </div>
                    )}
                  </div>
                )}
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-slate-300 mb-2">
                Subject
              </label>
              <input
                type="text"
                value={subject}
                onChange={(e) => setSubject(e.target.value)}
                className="w-full px-3 py-2 bg-slate-700 text-slate-200 rounded-lg border border-slate-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                placeholder="Enter email subject"
              />
            </div>

            {resultsImage && (
              <div className="flex items-center gap-3">
                <input
                  type="checkbox"
                  id="include-attachment"
                  checked={includeAttachment}
                  onChange={(e) => setIncludeAttachment(e.target.checked)}
                  className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-slate-600 rounded"
                />
                <label htmlFor="include-attachment" className="text-slate-300">
                  Attach results image
                </label>
              </div>
            )}

            <div>
              <label className="block text-sm font-medium text-slate-300 mb-2">
                Race Report Preview
              </label>
              <div className="p-4 bg-slate-700/50 rounded-lg border border-slate-600 max-h-60 overflow-y-auto">
                <p className="text-slate-200 text-sm whitespace-pre-wrap">{raceReport || 'No race report available'}</p>
              </div>
            </div>
          </div>
        </div>

        <div className="flex justify-end gap-3 px-8 py-6 bg-gradient-to-r from-slate-800/80 to-slate-700/80 border-t border-slate-600/50">
          <button
            onClick={onClose}
            className="px-6 py-2.5 bg-slate-700 text-slate-200 rounded-lg hover:bg-slate-600 transition-all font-medium"
          >
            Cancel
          </button>
          <button
            onClick={handleShareResults}
            disabled={sending}
            className="flex items-center gap-2 px-6 py-2.5 bg-gradient-to-r from-blue-600 to-blue-700 text-white rounded-lg hover:from-blue-700 hover:to-blue-800 transition-all disabled:opacity-50 disabled:cursor-not-allowed shadow-lg hover:shadow-xl font-medium"
          >
            {sending ? (
              <>
                <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
                <span>Sending...</span>
              </>
            ) : (
              <>
                <Send size={18} />
                <span>Send Email</span>
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
};
